stages:
  - setup
  - test

setup:
  stage: setup
  script:
  - apt-get update -qy
  - apt-get install -y python3 python3-pip gfortran jq
  - pip3 install -r requirements.txt
  - pip3 install coverage pytest


test:
  stage: test
  script:
  - coverage run -m pytest
  - coverage xml -o cobertura.xml
  - bash <(curl -Ls https://coverage.codacy.com/get.sh)

