stages:
  - test

test:
  stage: test
  script:
  - apt-get install -y python3 python3-pip gfortran jq
  - pip3 install -r requirements.txt
  - pip3 install coverage pytest
  - coverage run -m pytest
  - coverage xml -o cobertura.xml
  - bash <(curl -Ls https://coverage.codacy.com/get.sh)
