language: python
python:
# - '3.6'
- '3.7'
- '3.8'
before_install:
- sudo apt-get -y install gfortran jq
- LATEST_VERSION="$(wget -q -O - https://api.bintray.com/packages/codacy/Binaries/codacy-coverage-reporter/versions/_latest | jq -r .name)"
- wget -O codacy-coverage-reporter "https://dl.bintray.com/codacy/Binaries/${LATEST_VERSION}/codacy-coverage-reporter-linux"
- chmod +x codacy-coverage-reporter
install:
- pip install -r requirements.txt
- pip install coverage
script:
- coverage run -m pytest
after_success:
- coverage xml -o cobertura.xml
- ./codacy-coverage-reporter report
