language: python
python:
# - '3.6'
- '3.7'
- '3.8'
before_install:
- sudo apt-get -y install gfortran
install:
- pip install -r requirements.txt
- pip install coverage
script:
- coverage run -m pytest
- coverage xml -o cobertura.xml
- bash <(wget -q -O - https://coverage.codacy.com/get.sh) 
