language: python
python:
# - '3.6'
- '3.7'
- '3.8'
before_install:
- sudo apt-get -y install gfortran jq
- LATEST_VERSION="$(wget -q -O - https://api.bintray.com/packages/codacy/Binaries/codacy-coverage-reporter/versions/_latest | jq -r .name)"
- wget -O codacy-coverage-reporter-assembly.jar "https://dl.bintray.com/codacy/Binaries/${LATEST_VERSION}/codacy-coverage-reporter-assembly.jar"
install:
- pip install -r requirements.txt
- pip install coverage
script:
- coverage run -m pytest
- coverage xml -o cobertura.xml
after_success:
- java -jar codacy-coverage-reporter-assembly.jar report -l Java -r build/reports/jacoco/test/jacocoTestReport.xml
