language: python
python:
- '3.6'
before_install:
- sudo apt-get install gfortran jq
install:
- pip install -r requirements.txt
- pip install coverage
script:
- coverage run pytest
- coverage xml -o cobertura.xml
- bash <(curl -Ls https://coverage.codacy.com/get.sh)

